# configs/jbshield.yaml
defender_type: JBShield

model: "/gemini/code/tele/models/vicuna-7b-v1.5"
model_name: "vicuna-7b-v1.5"
jailbreak_variant: "gcg"
# asset_root can be provided to override the default JBShield assets directory.
asset_root: "/gemini/code/tele/telesafety_defense/method_utils/JBShield"
