# Dataset Configuration
data_path: /data/xiuyuan/workspace/tele-safety/attack/questions_with_category.json

# Target Model Configuration
target_model_type: local  # Options: openai, local
target_model_name: Qwen2.5-3B
target_model_path: Qwen/Qwen2.5-3B-Instruct   # For local models only

# Auxiliary Model Configuration (for attacks like PAIR)
attack_model_type: local
attack_model_name: Qwen2.5-3B
attack_model_path: Qwen/Qwen2.5-3B-Instruct

eval_model_type: NULL

# Results Configuration
res_save_path: ./results/attack_result.jsonl

